jekyll:
  build: ./jekyll
  volumes_from:
    - nginx

certbot:
  image: certbot/certbot
  entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  volumes:
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot

a-sip-of-microservice:
  build: ./a-sip-of-microservice
  volumes_from:
    - nginx

nginx:
  build: ./nginx
  command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    - /var/www/blog
    - /var/www/gitbook
    - "./etc/nginx/site-enabled/draveness.me.conf:/nginx/draveness.me.conf"
    - "./etc/nginx/site-enabled/microservice-gitbook.conf:/nginx/microservice-gitbook.conf"
