FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
# COPY draven.co.conf /etc/nginx/site-enabled/draven.co.conf 
COPY draveness.me.conf /etc/nginx/site-enabled/draveness.me.conf 
COPY microservice-gitbook.conf /etc/nginx/site-enabled/microservice-gitbook.conf 
EXPOSE 80 443
